{% set name = "zc.buildout" %}
{% set version = "2.13.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e12fe3adf2e60f52da98c8db4630688b94cb1aad466b2c6a4a6e0fe40ea8f94a

build:
  number: 1
  entry_points:
    - buildout=zc.buildout.buildout:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools >=8.0,<52
  run:
    - python
    - setuptools >=8.0,<52

test:
  imports:
    - zc
    - zc.buildout
  commands:
    - buildout --help

about:
  home: http://buildout.org
  license: ZPL-2.1
  license_family: OTHER
  license_file: LICENSE.txt
  summary: System for managing development buildouts
  doc_url: http://www.buildout.org/en/latest/
  dev_url: https://github.com/buildout/buildout

extra:
  recipe-maintainers:
    - 183amir
    - lcolbois
